<?php
# This file was automatically generated by the MediaWiki 1.45.3
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.

if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

$wgSitename = "WESOVIETWIKI";
$wgScriptPath = "";
$wgServer = "https://wesovietwiki.onrender.com";
$wgResourceBasePath = $wgScriptPath;

$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
	'icon' => "$wgResourceBasePath/resources/assets/change-your-logo-icon.svg",
];

$wgEnableEmail = true;
$wgEnableUserEmail = true;
$wgEmergencyContact = "";
$wgPasswordSender = "";
$wgEnotifUserTalk = false;
$wgEnotifWatchlist = false;
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "postgres";
$wgDBserver = "dpg-d7uo0o1kh4rs73act9h0-a";
$wgDBname = "mediawiki_gp79";
$wgDBuser = "mediawiki";
$wgDBpassword = "y9Bnqlv0kiAg94n1HUZkzumsPz0lU2Ya";
$wgDBport = "5432";

$wgEnableUploads = false;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";
$wgUseInstantCommons = false;
$wgPingback = true;
$wgLanguageCode = "ko";
$wgLocaltimezone = "UTC";

$wgSecretKey = "ac6f1331248aa844fc8e9deaca8dc8fefdaf9feefdec6f02824738fa7f1a763b";
$wgAuthenticationTokenVersion = "1";
$wgUpgradeKey = "eb1bfe73da85c0e4";

$wgRightsPage = "";
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

$wgDiff3 = "/usr/bin/diff3";
$wgDefaultSkin = "vector-2022";

# Enabled skins.
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );
